### ISSUE TITLE
Is it possible to use this plugin for android 4.4 mobile app?

### ISSUE THREAD

**Issue by yecicen** [vincentmorneau/animapex#10]
First of all thank you for creating this amazing plugin, we're trying to develop android application with apex using 'basic>flash animation', I wonder that can this code also work on Android 4.4 Kitkat for tablet devices?

**Comment by vincentmorneau** [comment]
Hi, thanks for creating this issue!

First of all, can you provide a little context around your issue? Have you tried with an Android 4.4 device and it's not working? Is it just the flash or all animations are not working?

I don't have an Android 4.4 with me, so a GIF of the problem would be ideal. Or maybe you know a simulator I can use?

**Comment by yecicen** [comment]
Hi,

We tried with Android 4.4 device and it is not working, unfortunately. We are using only the flash animation. There is no blinking in the screen which we needed.

Our development environment is Oracle APEX with Cordova via Android Studio.

For testing you can use Ripple Emulator

**Comment by yecicen** [comment]
Hi again, I believe the problem is that Cordova is using Chromium 33 for Android 4.4 developments which has bugs for supporting css animations. We added small script for detecting OS and if animations not supported then use native javascript functions for toggle operations such as display:none. I believe jQuery's show and hide methods will also work. Thanks for your replies :)

**Comment by vincentmorneau** [comment]
I see, it's always hard to support older browser versions. Glad you can achieve your flashing behavior with jQuery hide and show. Are you okay if I close this?

**Comment by yecicen** [comment]
Yes, you can close this, thanks again.
